<?php
/**
 * @var mixed $data Custom data for the template.
 */
wp_enqueue_script( $data->plugin_name . '-moment' );
wp_enqueue_script( $data->plugin_name . '-fullcalendar' );
wp_enqueue_script( $data->plugin_name . '-qtip' );
wp_enqueue_script( 'wfea-image-calendar' );
wp_enqueue_script( $data->plugin_name . '-locale' );
wp_enqueue_style( $data->plugin_name . '-fullcalendar-css' );
wp_enqueue_style( $data->plugin_name . '-fullcalendar-print-css' );
wp_enqueue_style( $data->plugin_name . '-qtip-css' );
wp_enqueue_style( 'wfea-image-calendar-style' );

$caloptions = array(
	'header'              => array(
		'left'   => 'month,agendaWeek',
		'center' => 'title',
		'right'  => 'prev,next'
	),
	'titleRangeSeparator' => ' - ',
	'height'              => 'auto',
	'locale'              => \WidgetForEventbriteAPI\FrontEnd\FrontEnd::get_cal_locale(),
);
// Recent posts wrapper.
printf( '<section %1$s class="wfea %2$s">',
	( ! empty( $data->args['cssID'] ) ? 'id="' . sanitize_html_class( $data->args['cssID'] ) . '"' : '' ),
	( ! empty( $data->args['css_class'] ) ? '' . sanitize_html_class( $data->args['css_class'] ) . '' : '' )
);


if ( false !== $data->events && $data->events->have_posts() ) :
	$earliest_start = 86400;
	$latest_end     = 0;

// add events
	$i = 0;
	while ( $data->events->have_posts() ): $data->events->the_post();
		if ( 0 == $i ) {
			$caloptions['defaultDate'] = eventbrite_event_start()->local;
		}
		$i ++;
		$caloptions['events'][] = array(
			'imageurl'         => esc_url( $data->events->post->logo_url ),
			'start'   => eventbrite_event_start()->local,
			'end'     => eventbrite_event_end()->local,
			'excerpt'          => wp_trim_words( get_the_excerpt(), 20, ' &hellip;' ),
			'url'              => esc_url( eventbrite_event_eb_url( ( $data->args['tickets'] ) ? '#tickets' : '' ) )
		);
		$parsed                 = date_parse( eventbrite_event_start()->local );
		$start                  = $parsed['hour'] * 3600 + $parsed['minute'] * 60 + $parsed['second'];
		$parsed                 = date_parse( eventbrite_event_end()->local );
		$end                    = $parsed['hour'] * 3600 + $parsed['minute'] * 60 + $parsed['second'];
		if ( $start < $earliest_start ) {
			$earliest_start = $start;
		}
		if ( $end > $latest_end ) {
			$latest_end = $end;
		}
	endwhile;
	$caloptions['minTime'] = gmdate( "H:i:s", $earliest_start );
	$caloptions['maxTime'] = gmdate( "H:i:s", $latest_end );


endif;

wp_localize_script( 'wfea-image-calendar', 'WFEACalendarImg', $caloptions );

?>
    <div class='wfea-calendar-img-cal <?php echo ( $data->args['newtab'] ) ? 'newtab' : 'sametab'; ?>'></div>
    </section><!-- Generated by http://wordpress.org/plugins/widget-for-eventbrite-api/ -->
<?php

